In [1]:
import torch

### 1.入门

In [2]:
x = torch.arange(12)

In [4]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
x.dtype,x.numel(),x.size(),x.shape

(torch.int64, 12, torch.Size([12]), torch.Size([12]))

In [10]:
y = x.reshape(3,4)

In [11]:
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
y.size(),y.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [15]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
torch.randn((3,4))

tensor([[-0.4382, -1.2764,  1.1167, -0.4066],
        [-0.1997, -1.8322, -0.8694, -2.3023],
        [-0.6320,  0.4658, -0.7159, -1.4825]])

In [20]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.运算符

#### 2.1 两个张量维度一致

In [21]:
x = torch.Tensor([1.0,2,4,8])

In [22]:
y = torch.Tensor([2,2,2,2])

In [23]:
x+y

tensor([ 3.,  4.,  6., 10.])

In [24]:
x-y

tensor([-1.,  0.,  2.,  6.])

In [25]:
x*y

tensor([ 2.,  4.,  8., 16.])

In [26]:
x/y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [27]:
x**y

tensor([ 1.,  4., 16., 64.])

In [28]:
x.dtype,y.dtype

(torch.float32, torch.float32)

In [29]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [34]:
torch.exp(torch.Tensor([0]))

tensor([1.])

#### 2.2 cat

In [35]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))

In [36]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [37]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [38]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
X.sum(),Y.sum()

(tensor(66.), tensor(30.))

### 3. 广播机制

在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 这种机制的工作方式如下：
- 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
- 对生成的数组执行按元素操作。

在大多数情况下，我们将沿着数组中长度为1的轴进行广播，如下例子：

In [42]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [43]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 4. 索引和切片

In [44]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [45]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [49]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [50]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [51]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [52]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 5.节省内存

In [66]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))

In [67]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [68]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [69]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [70]:
id(Y)

3182838574752

In [71]:
Y = Y+X

In [72]:
Y

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])

In [73]:
id(Y)

3182838573456

In [74]:
Z = torch.zeros_like(Y)

In [75]:
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [76]:
id(Z)

3182843685408

In [77]:
Z[:] = X+Y

In [78]:
id(Z)

3182843685408

In [79]:
Z

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [81]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [82]:
id(X)

3182838835240

In [83]:
X+=Y

In [84]:
X

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [85]:
id(X)

3182838835240

----------------------------------------------------------
实验

In [86]:
X1 = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y1 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [87]:
id(X1)

3182843625408

In [88]:
X1 = X1+Y1

In [89]:
id(X1)

3182853708032

In [90]:
X2 = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y2 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [91]:
id(X2)

3182853708608

In [93]:
X2+=Y2

In [94]:
id(X2)

3182853708608

### 6.类型转换

In [95]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [96]:
A

array([[ 2.,  3.,  8.,  9.],
       [ 9., 12., 15., 18.],
       [20., 21., 22., 23.]], dtype=float32)

In [97]:
B

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。

In [98]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 练习
1. 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。
2. 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

#### 1. 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。

In [108]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [109]:
Y = torch.Tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [112]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [113]:
X>Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [114]:
X<Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

#### 2.用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [121]:
x = torch.randn((1,2,3))

In [122]:
x

tensor([[[-0.1727, -1.5709, -0.1156],
         [ 0.1486,  0.2829, -0.4702]]])

In [123]:
y = torch.randn((2,2,1))

In [124]:
y

tensor([[[-1.0123],
         [ 0.1108]],

        [[-0.9509],
         [-1.4275]]])

In [130]:
z = x+y
z

tensor([[[-1.1850, -2.5832, -1.1279],
         [ 0.2595,  0.3938, -0.3593]],

        [[-1.1235, -2.5218, -1.0665],
         [-1.2788, -1.1446, -1.8976]]])

In [127]:
z.shape

torch.Size([2, 2, 3])