### 1.标量

In [2]:
import torch

In [11]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

In [10]:
x,x.dtype,x.shape

(tensor(3.), torch.float32, torch.Size([]))

In [12]:
y

tensor(2.)

In [13]:
x+y,x-y,x*y,x/y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000))

### 2.向量

In [17]:
x = torch.arange(4)
x,x[3],x.dtype

(tensor([0, 1, 2, 3]), tensor(3), torch.int64)

In [18]:
len(x)

4

In [20]:
x.shape

torch.Size([4])

In [24]:
x.ndim

1

### 3.矩阵

In [25]:
A = torch.arange(20).reshape(5,4)

In [26]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [27]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵

In [28]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

In [29]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [30]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 4.张量

In [31]:
X = torch.arange(24).reshape(2, 3, 4)

In [32]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

#### 4.1 张量算法的基本性质

In [33]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [34]:
id(A),id(B)

(2452631963040, 2452631964048)

In [35]:
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [37]:
A*B  #两个矩阵的按元素乘法称为Hadamard积（Hadamard product）

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [38]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [39]:
a*X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

### 5.降维

In [52]:
x  = torch.arange(4,dtype=torch.float32)

In [53]:
x

tensor([0., 1., 2., 3.])

In [54]:
x.sum()

tensor(6.)

In [63]:
A = torch.arange(20,dtype=torch.float32).reshape(5, 4)
A,A.dtype

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.float32)

In [64]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [65]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0

tensor([40., 45., 50., 55.])

In [66]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1

tensor([ 6., 22., 38., 54., 70.])

In [67]:
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

In [68]:
A.sum() / A.numel()

tensor(9.5000)

In [69]:
A.mean()

tensor(9.5000)

In [70]:
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [71]:
A.sum(axis=0) / A.shape[0]

tensor([ 8.,  9., 10., 11.])

#### 5.1 非降维求和

In [73]:
A,A.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]))

In [75]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A,sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [76]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [77]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [78]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 6.点积

In [79]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [80]:
torch.sum(x*y)

tensor(6.)

### 7.向量积

In [81]:
A,x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [82]:
A.shape,x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [83]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

### 8.矩阵乘法

In [84]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [86]:
B = torch.ones(4,3)
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [87]:
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 9.范数

L2范数

In [88]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

L1范数

与L2范数相比，L1范数受异常值的影响较小。 为了计算L1范数，我们将绝对值函数和按元素求和组合起来。

In [90]:
torch.abs(u).sum()

tensor(7.)

In [91]:
torch.norm(torch.ones((4, 9)))

tensor(6.)